# Generated by Django 6.0.3 on 2026-04-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMULocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')])),
                ('post_datetime', models.DateTimeField()),
                ('post_itemcategory', models.CharField(choices=[('electronics', 'Electronic Devices'), ('stationary', 'Stationaries'), ('wallet', 'Wallets'), ('card', 'Cards'), ('bottle', 'Water Bottles'), ('bag', 'Bags'), ('key', 'Keys'), ('umbrella', 'Umbrellas'), ('keychain', 'Keychains'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('other', 'Other Items')], max_length=100)),
                ('post_description', models.TextField()),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.mmulocation')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
