# Generated by Django 6.0.3 on 2026-04-16 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_mmulocation_post_delete_itemcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmulocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mmulocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
